name: Latest medium blog posts workflow       # This is a basic workflow to help you get started with Actions
on: # Controls when the workflow will run
  schedule: #Automatically run workflow
    - cron: '0 0 * * *' #Run everyday at 12 am UTC
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:        # Steps represent a sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@v2             # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@adewalade"

